name: motorsync
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^6.0.6
  google_fonts: ^6.1.0

  #UI
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  package_info_plus: ^4.2.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.3.5

  #STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  #STORAGE & PERMISSION
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  provider: ^6.0.5

  #CONNECTIVITY
  http: ^1.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  store_redirect: ^2.0.1

  #Firebase
  firebase_in_app_messaging: ^0.7.4+2
  firebase_messaging: ^14.7.2
  firebase_core: ^2.20.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.3

  # ADS
  google_mobile_ads: ^3.1.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.8.0

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
